#!/usr/bin/env python3
"""Add a staff row to a course's LOCAL roster, for testing against real data.

Now that access is enforced per course, the bundled IdP personas can only reach
a course whose roster is synthetic — they are not in a real imported one, so
they get a 403. This adds a matching staff row so a persona can sign in to a
course carrying the real roster.

Local development only. It writes to data/<COURSE>/ in the working copy, which is
gitignored and guarded by the pre-commit hook; production rosters come from
makeJSON.py and are never touched by this. A re-import (`ddev roster-real <COURSE>`) regenerates the file
from the spreadsheet and drops the row, so re-run this afterwards.

The row is built the way makeJSON.py builds one: an admin role (Professor/GTAs)
gets every group plus the full evaluator list, and is itself added to every other
admin's evaluator list.
"""
import argparse
import json
import os
import sys

# The IdP reads users-app.php; the tool keeps its own registry beside it so it
# can ADD a login without having to parse PHP back. Both are gitignored — these
# are per-developer identities, not project configuration (see the .sample).
#
# Reached through the project mount, not /mnt/ddev_config: that copy of .ddev is
# read-only inside the web container. Both paths are the same files on the host.
IDP_CONFIG = "/var/www/html/.ddev/shib-idp/config"
IDP_USERS_PHP = os.path.join(IDP_CONFIG, "users-app.php")
IDP_REGISTRY = os.path.join(IDP_CONFIG, "users-app.local.json")


def write_idp_login(netid, name, password):
    """Register a login with the bundled test IdP, keeping any already there."""
    logins = {}
    if os.path.isfile(IDP_REGISTRY):
        with open(IDP_REGISTRY) as fh:
            logins = json.load(fh)

    first, _, rest = name.partition(" ")
    logins[netid] = {
        "password": password,
        "cn": netid,
        "eppn": f"{netid}@stonybrook.edu",
        "mail": f"{netid}@stonybrook.edu",
        "givenName": first,
        "nickname": first,
        "sn": rest or "Test TA",
        "displayName": name,
        "affiliation": "employee@stonybrook.edu",
    }

    with open(IDP_REGISTRY, "w") as fh:
        json.dump(logins, fh, indent=4, sort_keys=True)

    lines = [
        "<?php",
        "// GENERATED by `ddev add-test-ta` from users-app.local.json — do not edit.",
        "// Per-developer test logins for the bundled IdP; gitignored on purpose.",
        "// See .ddev/tahelper/users-app.sample.php for the shape and the why.",
        "return [",
    ]
    for uid, u in sorted(logins.items()):
        lines.append(f"    '{uid}:{u['password']}' => [")
        for attr in ("cn", "eppn", "mail", "givenName", "nickname", "sn",
                     "displayName", "affiliation"):
            lines.append(f"        '{attr}' => [{json.dumps(u[attr])}],")
        lines.append("    ],")
    lines += ["];", ""]

    # Must be world-readable. The IdP image is built from this directory and
    # SimpleSAMLphp reads the file as www-data, so a 0600 copy makes the whole
    # login flow fail with a 500 instead of showing a form. It has to be created
    # that way rather than chmod-ed afterwards: the file sync carries content to
    # the host but not a later mode change, and the image is built from the
    # host's copy. Not a secret — local test logins only.
    old_umask = os.umask(0o022)
    try:
        with open(IDP_USERS_PHP, "w") as fh:
            fh.write("\n".join(lines))
        os.chmod(IDP_USERS_PHP, 0o644)
    finally:
        os.umask(old_umask)
    return len(logins)

ADMIN_ROLES = ("Professor", "GTAs")
ROLES = ADMIN_ROLES + ("Group Facilitator",)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("course")
    ap.add_argument("netid")
    ap.add_argument("name", nargs="+", help="display name, e.g. Sample TA")
    ap.add_argument("--type", dest="role", default="GTAs", choices=ROLES)
    ap.add_argument("--storage", default="/var/www/html/data")
    ap.add_argument("--password", help="IdP password (default: <netid>pass)")
    ap.add_argument("--no-idp", action="store_true",
                    help="only touch the roster; leave the IdP logins alone")
    args = ap.parse_args()

    name = " ".join(args.name)
    path = os.path.join(args.storage, args.course, "json", "data.json")
    if not os.path.isfile(path):
        raise SystemExit(f"No roster for {args.course} at {path}.\n"
                         f"Import one first:  ddev roster-real {args.course}"
                         f"   (or: ddev roster {args.course})")

    with open(path) as fh:
        data = json.load(fh)

    staff = data.setdefault("TA Groups", {})
    students = data.get("Student Groups", {})

    # Every group id the roster mentions, ordered the way makeJSON.py orders them:
    # by group number within a section, then by section.
    groups = {s["Group"] for s in students.values() if s.get("Group")}
    for member in staff.values():
        groups.update(member.get("Group") or [])
    groups = sorted(groups, key=lambda g: (g.split("-")[0], int(g.split("-")[1])
                                           if g.split("-")[-1].isdigit() else 0))

    staff[args.netid] = {
        "Name": name,
        "NetID": args.netid,
        "Type": args.role,
        "Group": groups if args.role in ADMIN_ROLES else [],
        "GTAGroups": [],
    }

    # Evaluator lists: admins can evaluate on behalf of any staff member, so the
    # new row has to appear in theirs and they in its.
    evaluators = sorted(({"Name": m["Name"], "NetID": m["NetID"]} for m in staff.values()),
                        key=lambda e: e["NetID"])
    for member in staff.values():
        if member.get("Type") in ADMIN_ROLES:
            member["Evaluators"] = [dict(e) for e in evaluators]

    with open(path, "w") as fh:
        json.dump(data, fh, sort_keys=True, indent=4, separators=(",", ": "))

    print(f"{args.course}: added '{args.netid}' ({name}) as {args.role}")
    print(f"  groups     : {len(staff[args.netid]['Group'])}")
    print(f"  staff now  : {len(staff)}")
    print(f"  written to : {path}  (local storage, outside the repo)")
    if not args.no_idp:
        total = write_idp_login(args.netid, name, args.password or f"{args.netid}pass")
        print(f"  IdP login  : {args.netid} / {args.password or args.netid + 'pass'} "
              f"({total} local login(s) registered)")
        print("  Run 'ddev restart' for the IdP to pick it up.")
    print("  NOTE: a re-import with 'ddev roster-real' regenerates the roster from the")
    print("        spreadsheet and drops this row — re-run this command afterwards.")


if __name__ == "__main__":
    sys.exit(main())
